#ifndef CWB_CONF_H_INC
#define CWB_CONF_H_INC

#define CWB_CONF_EVENT_FD_MAX_NUM 64

#define CWB_CONF_DSTR_PARTSIZE 16384

#define CWB_CONF_BUFFER_PARTSIZE 16384

#define CWB_CONF_COROUTINE_STKSIZE 8192

#define CWB_CONF_HTTPD_BACKLOG 1024

#endif
